###POST
POST http://localhost:3000/produtos 

Content-Type: application/json
{
    "nome": "Teste 2",
    "descricao": "Descrição teste 2",
    "preco": 25.90
}

### GET
GET http://localhost:3000/produtos 

### GET
GET http://localhost:3000/produtos/3

### PATCH
PATCH http://localhost:3000/produtos/3

Content-Type: application/json
{
    "nome": "Teste 3",
    "descricao": "Descrição teste 3",
    "preco": 55.0
}

### DELETE
DELETE http://localhost:3000/produtos/3